### ISSUE TITLE
mp4录制的样例有吗？

### ISSUE THREAD

**Issue by myroom123** [1461521844lijin/trt_yolo_video_pipeline#10]
请问一下有mp4录制的样例吗？

还有请问一下识别推流的结构化数据可以获取吗？我想用来做track id

**Comment by 1461521844lijin** [comment]
[record_example.cpp](https://github.com/1461521844lijin/trt_yolo_video_pipeline/blob/main/test/record_example.cpp)
视频录制样例补充
