### ISSUE TITLE
能实现多级推理么？

### ISSUE THREAD

**Issue by piaolinzhe** [1461521844lijin/trt_yolo_video_pipeline#12]
希望能有多级推理的案例

**Comment by piaolinzhe** [comment]
还有可视化管道功能，方便调试

**Comment by 1461521844lijin** [comment]
> 希望能有多级推理的案例

你指的是多个模型的串行调用吗 再写一个推理节点接上整个pipeline去就好了 如果我后面有空倒是可以多写一些例子出来

**Comment by 1461521844lijin** [comment]
> 还有可视化管道功能，方便调试

这个功能以后也不计划支持，比较麻烦； 想要这个功能推荐用video_pipe_c  

性能调试可以输出日志
