### ISSUE TITLE
您好，请问能实现多路视频流，单实例，多batch推理吗

### ISSUE THREAD

**Issue by songsong695** [1461521844lijin/trt_yolo_video_pipeline#13]
您好，对c++不太熟悉，想请问这个代码能实现只实例化一个模型，但是接入多路视频流，多batch去推理吗？谢谢！

**Comment by 1461521844lijin** [comment]
可以的 这个需求我这个项目可以覆盖

**Comment by songsong695** [comment]
> 可以的 这个需求我这个项目可以覆盖

好的，谢谢您的解答。发现输入流路径input_stream_url是个字符串类型，如果我要实现多路的话，请问是多创建几个pipline吗，然后每个pipline输入不同的流地址是吗？谢谢！

**Comment by 1461521844lijin** [comment]
> > 可以的 这个需求我这个项目可以覆盖
> 
> 好的，谢谢您的解答。发现输入流路径input_stream_url是个字符串类型，如果我要实现多路的话，请问是多创建几个pipline吗，然后每个pipline输入不同的流地址是吗？谢谢！

是的，创建不同的pipeline，每个pipeline就是一路流，吧你实例化的模型传入pipeline作为参数即可

**Comment by songsong695** [comment]
> > > 可以的 这个需求我这个项目可以覆盖
> > 
> > 
> > 好的，谢谢您的解答。发现输入流路径input_stream_url是个字符串类型，如果我要实现多路的话，请问是多创建几个pipline吗，然后每个pipline输入不同的流地址是吗？谢谢！
> 
> 是的，创建不同的pipeline，每个pipeline就是一路流，吧你实例化的模型传入pipeline作为参数即可

好的，十分感谢！！
