### ISSUE TITLE
检测后加多个分类模型

### ISSUE THREAD

**Issue by Hongyuan-Liu** [1461521844lijin/trt_yolo_video_pipeline#16]
你好，对于检测算法后面跟着多个分类算法，该如何优雅、高效的实现，比如某一帧的检测结果，有人、手机、安全帽三种类别的目标，其中人目标不进行分类，手机、安全帽目标需要分别用两个分类算法进行二分类，以再次确认，减少误报。也就是某一帧首先要经过检测模型，然后再进行抠图，分别送入两个分类模型，最终该帧的结果是分类结果与检测结果综合判断的结果，这样的流程该如何优雅、高效、并且通用的实现呢。

**Comment by 1461521844lijin** [comment]
> 你好，对于检测算法后面跟着多个分类算法，该如何优雅、高效的实现，比如某一帧的检测结果，有人、手机、安全帽三种类别的目标，其中人目标不进行分类，手机、安全帽目标需要分别用两个分类算法进行二分类，以再次确认，减少误报。也就是某一帧首先要经过检测模型，然后再进行抠图，分别送入两个分类模型，最终该帧的结果是分类结果与检测结果综合判断的结果，这样的流程该如何优雅、高效、并且通用的实现呢。

我能想到的就是检测模型和分类模型串行构建流水线，检测模型后面跟着两个并行的分类模型，将手机安全帽数据分别送入另外两个分类模型中进行并行处理，结果汇总时需要注意数据同步问题。
![Uploading Snipaste_2024-05-19_10-39-18.png…]()

**Comment by Hongyuan-Liu** [comment]
期待大佬后续多级模型实现
