### ISSUE TITLE
I have to have a GPU, right?

### ISSUE THREAD

**Issue by YoungjaeDev** [1461521844lijin/trt_yolo_video_pipeline#17]
Can I do a multi-video pipeline without a GPU?

**Comment by 1461521844lijin** [comment]
If you want to use this project without using GPU,  need to rewrite InferInstance yourself

The example in project is TRT

**Comment by YoungjaeDev** [comment]
@1461521844lijin 
Forgive me for asking about your project without running it yet, but I was wondering if I could take the openvino model and integrate it into the multi-pipeline you have implemented.

**Comment by 1461521844lijin** [comment]
> @1461521844lijin Forgive me for asking about your project without running it yet, but I was wondering if I could take the openvino model and integrate it into the multi-pipeline you have implemented.

Yes, you can refer to the example of ‘YoloDetectionInfer.cpp’ in the project to rewrite an openvino instance.
