### ISSUE TITLE
存储内存泄漏

### ISSUE THREAD

**Issue by Discovery-Kingdom** [1461521844lijin/trt_yolo_video_pipeline#18]
Enmuxer::~Enmuxer() {
    m_format_ctx = nullptr;
    close();
}
应删除 m_format_ctx = nullptr;

**Comment by 1461521844lijin** [comment]
我之后修复，感谢

**Comment by SoulProficiency** [comment]
> Enmuxer::~Enmuxer() { m_format_ctx = nullptr; close(); } 应删除 m_format_ctx = nullptr;

请问为何删除后可以防止存储内存泄露？
