### ISSUE TITLE
N-1-N_example.cpp

### ISSUE THREAD

**Issue by i923002** [1461521844lijin/trt_yolo_video_pipeline#19]
在N-1-N_example.cpp中

std::vector<int> device_list{0, 0, 0}; 代表甚麼意思?
是指3張顯卡都偵測0,而0代表Person嗎?

**Comment by 1461521844lijin** [comment]
device_list的长度是实例化是数量，列表里的值是显卡下标，0就是第0张卡，标识这个实例创建在哪张卡上
std::vector device_list{0, 0, 0}; 代表在0卡上创建3个推理实例
std::vector device_list{0, 1}; 则是0卡上一个实例，1卡上一个实例
