### ISSUE TITLE
能适配Nvidia Jetson的硬件吗，当前在Jetson Orin Nano跑会报错

### ISSUE THREAD

**Issue by wufulin** [1461521844lijin/trt_yolo_video_pipeline#25]
1、checkIfSupportedNvidia_l 没有/dev/nvidia
2、ffmpeg 没有h264_nvenc，需要使用h264_nvmpi

**Comment by 1461521844lijin** [comment]
抱歉我没有对应的硬件没法测试适配

也许需要你手动改一下代码：
包括需要注释掉checkIfSupportedNvidia，自行编译ffmpeg支持h264_nvmpi，还有在打开编解码器部分的代码上进行修改；可能还会有像素空间格式转换问题需要自行解决一下

**Comment by wufulin** [comment]
> 抱歉我没有对应的硬件没法测试适配
> 
> 也许需要你手动改一下代码： 包括需要注释掉checkIfSupportedNvidia，自行编译ffmpeg支持h264_nvmpi，还有在打开编解码器部分的代码上进行修改；可能还会有像素空间格式转换问题需要自行解决一下



> 抱歉我没有对应的硬件没法测试适配
> 
> 也许需要你手动改一下代码： 包括需要注释掉checkIfSupportedNvidia，自行编译ffmpeg支持h264_nvmpi，还有在打开编解码器部分的代码上进行修改；可能还会有像素空间格式转换问题需要自行解决一下


1、可以提供jetson硬件远程访问测试，该设备已经自行编译ffmpeg支持h264_nvmpi了

**Comment by wufulin** [comment]
![image](https://github.com/1461521844lijin/trt_yolo_video_pipeline/assets/1061221/238300c2-fc24-4a88-bc44-db510c58c05f)

**Comment by 1461521844lijin** [comment]
> ![image](https://private-user-images.githubusercontent.com/1061221/343089734-238300c2-fc24-4a88-bc44-db510c58c05f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzOTM2OTAsIm5iZiI6MTcxOTM5MzM5MCwicGF0aCI6Ii8xMDYxMjIxLzM0MzA4OTczNC0yMzgzMDBjMi1mYzI0LTRhODgtYmM0NC1kYjUxMGM1OGMwNWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjZUMDkxNjMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmU2YjcxMDExNjhkYzMyNjA5N2Q4YmFiYzQ0N2RmZmIwOTdhOWUyYzQzOGVlYzU4MTRmMDQxZDUxMmExZTA0MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.l_LjbsU25T0GcgDnPI7NO_kZGrpAbkNt3AfEhDhUumU)

这个问题有两个解决方案
1、升级你的ffmpeg版本确保跟我项目版本保持一致，
2、将demux.cpp中的关于超时连接配置的代码注释
![image](https://github.com/1461521844lijin/trt_yolo_video_pipeline/assets/34806114/58c3088a-11c0-4009-bd8f-fc3fdf489aa1)


老版本ffmpeg对于rtsp连接超时设置有bug，参考：https://trac.ffmpeg.org/ticket/2294

**Comment by wufulin** [comment]
> > ![image](https://private-user-images.githubusercontent.com/1061221/343089734-238300c2-fc24-4a88-bc44-db510c58c05f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzOTM2OTAsIm5iZiI6MTcxOTM5MzM5MCwicGF0aCI6Ii8xMDYxMjIxLzM0MzA4OTczNC0yMzgzMDBjMi1mYzI0LTRhODgtYmM0NC1kYjUxMGM1OGMwNWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjZUMDkxNjMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmU2YjcxMDExNjhkYzMyNjA5N2Q4YmFiYzQ0N2RmZmIwOTdhOWUyYzQzOGVlYzU4MTRmMDQxZDUxMmExZTA0MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.l_LjbsU25T0GcgDnPI7NO_kZGrpAbkNt3AfEhDhUumU)
> 
> 这个问题有两个解决方案 1、升级你的ffmpeg版本确保跟我项目版本保持一致， 2、将demux.cpp中的关于超时连接配置的代码注释 ![image](https://private-user-images.githubusercontent.com/34806114/343094453-58c3088a-11c0-4009-bd8f-fc3fdf489aa1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzOTY3OTcsIm5iZiI6MTcxOTM5NjQ5NywicGF0aCI6Ii8zNDgwNjExNC8zNDMwOTQ0NTMtNThjMzA4OGEtMTFjMC00MDA5LWJkOGYtZmMzZmRmNDg5YWExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDEwMDgxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0ZjY3MjdjMjhmOWVmZTJlZmZkZTIyMjlhNGJlODNmNDg1MGIzNmMyZWM3ZTZmZGEwMmMzMmU2MWY0ZTQ0ODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fJWS7AHt284d9Q85T3eB8NTjZhZxALxIYlVAeiT0iMk)
> 
> 老版本ffmpeg对于rtsp连接超时设置有bug，参考：https://trac.ffmpeg.org/ticket/2294

关于1：ffmpeg h264_nvmpi只支持ffmpeg 4.2、4.4、6.0版本，没有你原来5.1.2的版本，因为不是官方支持的，只是国外大神打补丁做的
关于2：我目前确实是注释掉解决的
