### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Hongyuan-Liu** [1461521844lijin/trt_yolo_video_pipeline#26]
你好，在录制mp4文件的时候，Enmux.cpp中的av_write_trailer被调用了两次，在Mp4RecordTask.cpp录制完成时调用了一次，在m_enmuxer对象析构的时候close调用了一次，出现Segmentation fault错误

**Comment by 1461521844lijin** [comment]
这个确实不应该调用2次，之前没报错是因为修复了一个Mp4RecordTask对象资源无法正确析构，现在析构后析构函数内部还会再调用一次，触发了这个问题

**Comment by 1461521844lijin** [comment]
> 你好，在录制mp4文件的时候，Enmux.cpp中的av_write_trailer被调用了两次，在Mp4RecordTask.cpp录制完成时调用了一次，在m_enmuxer对象析构的时候close调用了一次，出现Segmentation fault错误

已修复
