### ISSUE TITLE
when running long time, it may encounter a "ffmpeg rtmp broken pipe " error 

### ISSUE THREAD

**Issue by wufulin** [1461521844lijin/trt_yolo_video_pipeline#27]
![img_v3_02ce_84501427-d250-478c-80b2-292a619847dg](https://github.com/1461521844lijin/trt_yolo_video_pipeline/assets/1061221/989a4792-a1af-4685-823e-335d6d3b3fb5)

**Comment by 1461521844lijin** [comment]
可以拉取一下最新代码，里面有关于输出超时重连的逻辑；

**Comment by wufulin** [comment]
> 可以拉取一下最新代码，里面有关于输出超时重连的逻辑；

已经是拉了最新代码，这个输出超时重连的逻辑是哪个commit？

**Comment by wufulin** [comment]
> 可以拉取一下最新代码，里面有关于输出超时重连的逻辑；

ok，我看到了，要发生100次write packet error才会发生重连

**Comment by 1461521844lijin** [comment]
> > 可以拉取一下最新代码，里面有关于输出超时重连的逻辑；
> 
> ok，我看到了，要发生100次write packet error才会发生重连

这个100是随便设置的，你可以根据需要修改。
以前排查过这个问题产生的原因，由于推送端长时间没有向接收端推送数据，导致接收端关闭了连接；也可以对接收端的流媒体服务的超时时间进行配置，保持较长时间的连接

**Comment by 1461521844lijin** [comment]
> > 可以拉取一下最新代码，里面有关于输出超时重连的逻辑；
> 
> ok，我看到了，要发生100次write packet error才会发生重连

这个100是随便设置的，你可以根据需要修改。
以前排查过这个问题产生的原因，由于推送端长时间没有向接收端推送数据，导致接收端关闭了连接；也可以对接收端的流媒体服务的超时时间进行配置，保持较长时间的连接
