### ISSUE TITLE
trt_draw_node缓冲队列已满

### ISSUE THREAD

**Issue by myroom123** [1461521844lijin/trt_yolo_video_pipeline#8]
![image](https://github.com/1461521844lijin/trt_yolo_video_pipeline/assets/44058826/f336b45e-09bd-4b7c-be35-36534f1a1e44)
一直显示缓冲队列已满

**Comment by 1461521844lijin** [comment]
这是个bug，会在infer线程中有推理失败的情况下被触发，绘制线程那边会一直等待数据让缓存队列阻塞，我之后会修复一下

**Comment by 1461521844lijin** [comment]
> ![image](https://private-user-images.githubusercontent.com/44058826/294134558-f336b45e-09bd-4b7c-be35-36534f1a1e44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MzQ4MjUsIm5iZiI6MTcwNDQzNDUyNSwicGF0aCI6Ii80NDA1ODgyNi8yOTQxMzQ1NTgtZjMzNmI0NWUtMDliZC00YjdjLWJlMzUtMzY1MzRmMWExZTQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA2MDIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkYzg0NWFkZmY1MGZlMzAxYTc0MDA5OTU0ZGQ5YjBkOTMxYmU5N2I3NGYwYTRjM2Q2YzA3ZTcwODBkMWJjYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UoRy_aRRasYRMbxQEvvLUQ6SydjuoJDx-36bfEa5fuM) 一直显示缓冲队列已满

推理失败时会导致当次bacth的数据被丢弃，但渲染node会等待数据赋值导致那个地方阻塞，我加了超时时间，来过滤这个问题

出现这个问题的原因可能是你用的是静态batch模型，设置的最大batch数超过了模型的batch，导致单次调度时加载的batch数超过了模型支持的batch数。

或者其他原图导致的推理失败
